### ISSUE TITLE
Plugin "Could not load source for library"

### ISSUE THREAD

**Issue by LSNW** [cqframework/atom_cql_support#36] opened 2021-09-16 17:40 UTC
The plugin was highlighting a "could not load source for library" error for all my include statements. I ensured that versions were correct. Any statements that referenced the library would then also give an error. However, the code still ran normally.
![image](https://user-images.githubusercontent.com/52609843/133658329-4355b89f-dedb-435d-93c6-e732c78b2777.png)

Reinstalled several times and problem still persisted. However, I was eventually able to get a "fix" that I could replicate by performing the installation in the following order.
1 Uninstall atom-ide-ui then language-cql.
2 Restart Atom.
3 Install language-cql.
4 Open a folder, you'll be prompted to install the atom-ide-ui dependency. Click Yes.
5 After that has been installed, open a .cql file.
6 The cql language server will automatically install.

**Comment by brynrhodes** [comment] 2021-09-18 21:17
@LSNW, thank you for the issue report, we believe this was caused by a snapshot dependency in the language server that was inadvertently updated as part of releasing a new translator, engine, and evaluator. We have updated the dependency to reference the release versions and incremented and published a new version of the Atom plugin. Please update your plugin and that should address the issue.

**Comment by JPercival** [comment] 2022-01-03 00:04
Resolved by #40

**Closed as completed by JPercival** 2022-01-03 00:04 UTC
Labels: bug
