### ISSUE TITLE
Uncaught Error: Message header must separate key and value using :

### ISSUE THREAD

**Issue by frankadrian314159** [cqframework/atom_cql_support#41] opened 2022-01-04 14:52 UTC
I have removed the .Atom files in my home directory, loaded a new version of atom and have installed version 2.11.0 of language-cql.  I get this error whenever I load a cql file. I've attached a zipped copy of a file that's throwing this error:

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-cql](https://github.com/cqframework/atom_cql_support) package 2.11.0

### Stack Trace

Uncaught Error: Message header must separate key and value using :

```
At C:\Users\fadrian\.atom\packages\language-cql\node_modules\vscode-jsonrpc\lib\messageReader.js:57

Error: Message header must separate key and value using :
    at /packages/language-cql/node_modules/vscode-jsonrpc/lib/messageReader.js:57:23
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (/packages/language-cql/node_modules/vscode-jsonrpc/lib/messageReader.js:54:17)
    at StreamMessageReader.onData (/packages/language-cql/node_modules/vscode-jsonrpc/lib/messageReader.js:157:43)
    at /packages/language-cql/node_modules/vscode-jsonrpc/lib/messageReader.js:148:18)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

### Commands

```
     -2:34.4.0 application:open-folder (div.tool-panel.tree-view)
     -1:24.4.0 core:backspace (input.hidden-input)
     -1:18.7.0 core:page-up (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
ide-json 0.2.1 
json-colorer 1.0.0 
language-cql 2.11.0 
```
[snippets.zip](https://github.com/cqframework/atom_cql_support/files/7808438/snippets.zip)

**Comment by JPercival** [comment] 2022-01-10 21:58
Root cause was null pointer exception in upstream project (cql-language-server). Should be resolved in atom plugin release 2.11.1

**Closed as completed by JPercival** 2022-01-10 21:58 UTC
